GoogleCloudPlatform/cloud-run-release-manager

- internal/run/wrapper.go
The error message was based on the implementation of the package, and so it could be confusing to someone not familiar with the code.
> run: Improve message when client creation fails

- cmd/operator/main.go
- pkg/rollout/rollout.go
This is an attempt to start logging more information about the events occurring during the rollout process. It also adds the possibility to adjust the logging level through a CLI flag
> rollout: Log events in the rollout process

- pkg/config/config.go
This allows to specify metrics checks in the configuration. This will be used by the health package to determine if the candidate meets the metrics checks criteria
> config: Add metrics checks in configuration

- cmd/operator/service.go
- internal/run/wrapper.go
- internal/util/context.go
This lets the developer know that the list of regions were obtained from a cache. It also adds utility functions to set and get loggers to and from a context, which will also become useful when logging information about health and metrics.
> run: Log when cached regions are used

- go.mod
- go.sum
- internal/stackdriver/stackdriver.go
This uses the Cloud Monitoring package that has support for MQL queries, which will be useful when we start supporting any percentile for latency. The package used here is deprecated, so we should migrate to the new package once support for MQL queries is added to the new Cloud Monitoring package.
> stackdriver: Use package with RPC for MQL query

- cmd/operator/main.go
- pkg/config/config.go
- pkg/config/config_test.go
This adds support for metrics-related flags for health check. The new flags are: `-error-rate` (percent), `latency-p99` (ms), `latency-p95` (ms), and `latency-p50` (ms).
> main: Support metrics flags

- cmd/operator/main.go
- pkg/config/config.go
This removes the min/max values for metrics in the configuration since using a single value `threshold` makes the code simpler and cleaner
> config: Use thresholds for metrics

- internal/metrics/metrics.go
- internal/metrics/metrics_test.go
This adds a function to convert a supported percentile to an equivalent value for time series aligner/reducer
> metrics: Convert percentile to align/reduce value

- cmd/operator/main.go
- pkg/rollout/rollout.go
- pkg/rollout/rollout_test.go
This adds a dependency on a metrics provider for the rollout package. This provider will be used when retrieving the candidate's health.
> rollout: Receive a metrics provider in constructor

- internal/util/context.go
- internal/util/context_test.go
In a previous commit, a nil logger was supposed to be handled. However, the order of the check was reverted. This fixes this issue and handle cases in which the context does not have a logger value.
> util: Defend against panic when logger is nil

- internal/metrics/metrics.go
- internal/metrics/mock/metrics.go
- internal/stackdriver/stackdriver.go
This adds a function to the Metrics interface and adds an implementation in stackdriver to obtain the number of requests for a given offset.
> metrics: Obtain request count

- internal/stackdriver/stackdriver.go
This logs more information about what's going on when calling `Latency` and `ErrorRate` in stackdriver.
This also gets the latency for all types of responses as we previously discussed.
> stackdriver: Add logs in latency and error rate

- internal/metrics/metrics.go
- pkg/health/health.go
- pkg/health/health_test.go
This creates a new health package that has a main IsHealthy function to check if the metrics for the candidate revision meet the configuration criteria.
> health: Create package to determine health

- cmd/operator/main.go
- internal/metrics/metrics.go
- internal/metrics/mock/metrics.go
- internal/stackdriver/stackdriver.go
- internal/stackdriver/stackdriver_internal_test.go
- internal/stackdriver/stackdriver_test.go
- pkg/health/health.go
- pkg/health/health_test.go
The Query interface was always passed through the chain without changes to it, which makes it very hard to deduct its use. This removes the interface altogether and keep the filters as parameters of the provider constructor.
A new method SetCandidateRevision was added to the Provider interface since the candidate revision can only be determined during the rollout process. Furthermore, it looks like knowing the queried resource (i.e. the candidate revision) is necessary for any metrics provider.
> metrics: Remove the Query interface

- pkg/health/health.go
- pkg/health/health_test.go
This separates the collection of metrics values from the actual diagnosis of the health of the revision. It closes #30
> health: Separate metrics collection from diagnosis

- cmd/operator/main.go
- pkg/rollout/rollout.go
- pkg/rollout/rollout_test.go
This adds two methods that allows the update of the client and context used for rollouts. The context would become useful when we have to pass a context to the health package.
> rollout: Add methods to include client and context

- cmd/operator/main.go
- pkg/config/config.go
- pkg/config/config_test.go
This validates that the metrics criteria to err sooner for an invalid value. It also adds an extra return value in `config.IsValid` to specify the problem with the configuration object.
> config: Validate metrics criteria configuration

- cmd/operator/main.go
This concurrently rollouts all the services retrieved from the API.
> main: Make concurrent rollouts

- pkg/rollout/revision.go
- pkg/rollout/revision_test.go
- pkg/rollout/rollout.go
- pkg/rollout/rollout_test.go
This integrates with the health package to diagnose the candidate's health. If it is unhealthy, a rollback is performed.
> rollout: Rollback when candidate is unhealthy

- pkg/config/config.go
- pkg/rollout/rollout.go
- pkg/rollout/rollout_test.go
When reading the code, the name Metrics in the strategy is confusing. This renames this property to `HealthCriteria` for consistency across the code base and to make the code more readable.
> config: Change internal name for metrics criteria

- cmd/operator/main.go
- pkg/config/config.go
- pkg/config/config_test.go
This adds configuration and flag to specify the minimum number of requests needed to diagnose the candidate's health
> config: Add configuration for min request count

- pkg/health/health_test.go
This adds two test cases. One test is for all thresholds set at 0, while the second is for all metrics values being 0. This closes #31
> health: Add tests for thresholds and metrics at 0

- internal/metrics/sheets/sheets.go
- internal/run/wrapper.go
- internal/stackdriver/stackdriver.go
- internal/util/context.go
- internal/util/context_test.go
- pkg/health/health.go
Since it is clear we are getting the logger from the context, we can switch to a shorter name for the function. This closes #23
> util: Rename LoggerFromContext to LoggerFrom

- pkg/health/health.go
- pkg/health/health_internal_test.go
- pkg/health/health_test.go
This adds health criteria checks for request count. If the criteria is not met, an inconclusive diagnosis is returned.
> health: Check for request count

- cmd/operator/main.go
- cmd/operator/rollout.go
- cmd/operator/server.go
This creates an HTTP server when a port is specified using `-http-addr`. It also separates the rollout logic for reuse.
> main: Support rollouts through HTTP requests

- go.mod
- pkg/health/health.go
- pkg/health/report.go
- pkg/health/report_test.go
- pkg/rollout/revision.go
- pkg/rollout/rollout.go
- pkg/rollout/rollout_test.go
This adds annotation about the last health report. It uses the key rollout.cloud.run/lastHealthReport and assigns it a string with the last diagnosis (healthy, unhealthy) and the check results.
> rollout: Include health report in service object

- go.mod
- go.sum
- pkg/rollout/rollout.go
- pkg/rollout/rollout_test.go
This adds a new annotation containing the last time the traffic to the candidate was increased. Using the configuration for minimum time between roll forwards, it decides if it can continue rolling the candidate forward.
> rollout: Roll forward only if enough time passed

- cmd/operator/main.go
- internal/metrics/metrics.go
- internal/stackdriver/stackdriver.go
- pkg/health/health.go
When no request was made in the interval, Latency and ErrorRate returns errors that are propagated all the way to the main package. No requests shouldn't represent a metrics error.
> stackdriver: Return 0 if no request in interval

- cmd/operator/main.go
- cmd/operator/rollout.go
- cmd/operator/server.go
- cmd/operator/service.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/health/health.go
- pkg/health/health_test.go
- pkg/health/report.go
- pkg/health/report_test.go
- pkg/rollout/rollout.go
- pkg/rollout/rollout_internal_test.go
- pkg/rollout/rollout_test.go
As of now, the same rollout strategy was applied to all the targeted services. This makes changes to the configuration to allow different strategies for different targets.
> config: Allow multiple strategies

- cmd/operator/main.go
This modifies printHealthCriteria to make it print all the health criteria passed to it. That is, it removes the switch statement with a default case printing "invalid criterion". This is useful since once more metrics are supported, we don't need to worry about this function. Validation is done a few statements later anyways.
> main: Print all health criteria

- README.md
- cmd/operator/main.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/rollout/rollout.go
- pkg/rollout/rollout_test.go
This updates the type expected by the `cli-run-interval` and `healthcheck-offset` flags to time.Duration. This makes it more logical to the user and simplify our current implementation.
> main: Use time.Duration for time-related flags

- internal/rollout/rollout.go
- internal/rollout/rollout_test.go
- internal/rollout/traffic.go
- internal/rollout/traffic_test.go
This creates a new file traffic.go and move all the traffic-related methods to the new file. It also refactors the methods to return traffic configuration, so the main caller, UpdateService, can update the service's traffic.
> rollout: Update traffic in UpdateService

- cmd/operator/main.go
- go.mod
This uses the compute metadata package to detect the ID of the project on which the service is deployed. If the tool is not being run on GCE, it tries to detect the project ID by executing a `gcloud` command to get the default project
> main: Autodetect project if one is not specified

- README.md
This adds two roles in the instructions when deploying the Release Manager. The first allows to use other service accounts during updates. The second gives access to metrics to the Release Manager.
> Update instructions on permissions for the manager

- cmd/operator/main.go
- cmd/operator/rollout.go
Since this function is only used by another function in rollout.go, it doesn't make sense to have in main.go
> main: Move chooseMetricsProvider to rollout.go

- cmd/operator/main.go
This is with the purpose of showing more detail to the user about the configuration values for debug purposes. For now, we can print the command line flags
> main: Print flags

- internal/health/health.go
This includes the percentile field only for a latency criteria and renames "threshold" to "expectedValue"
> health: Update message for met/unmet criterion

- internal/rollout/rollout.go
This updates the log messages when no stable or candidate revision is found. It also changes the type of log to debug in the case of no candidate since it occurs often
> rollout: Change message when candidate is not found

- README.md
This updates the section on how the release manager works to mention that a label is required. It also explicitly mentions that the Cloud Run service should be run on the user's own GCP project
> Mention the required label selector

- README.md
This adds instructions of how to add labels to a service. It also clarifies the number of requests needed to evaluate the candidate's health
> Add label instructions local set-up section

- internal/health/health.go
The Diagnose function is currently not printing the actual value retrieved from the metrics, and instead has two similar fields `expectedValue` and `threshold`
> health: Log correct fields for criterion

- README.md
- cmd/operator/main.go
The previous value of 100 is an issue since it requires that the service gets a lot of requests, especially at the beginning of the rollout, to determine the candidate's health
> main: Default min requests to 0

- README.md
- cmd/operator/main.go
- internal/health/health.go
- internal/health/health_test.go
- internal/health/report.go
- internal/health/report_test.go
- internal/rollout/rollout.go
- internal/rollout/rollout_test.go
- internal/rollout/traffic.go
This reports the health for all possible cases. In particular, it reports inconclusive diagnosis (no enough requests) and healthy diagnosis without enough elapsed time.
> rollout: Report health for all cases

- go.mod
- go.sum
- internal/notification/pubsub/pubsub.go
- internal/pubsub/pubsub.go
This adds a pubsub package that adds a wrapper around the Google Cloud Pub/Sub package to publish rollout events
> pubsub: Add pubsub package for publishing events
